#!/usr/bin/sh

# Create ollama group if it doesn't exist
getent group ollama > /dev/null || groupadd -r ollama

# Create ollama user if it doesn't exist
getent passwd ollama > /dev/null || useradd -r -g ollama -c "Ollama Service Account" -d /usr/share/ollama -s /usr/sbin/nologin ollama

# Create and set permissions for required directories
install -d -m 755 -o ollama -g ollama /usr/share/ollama
install -d -m 755 -o ollama -g ollama /var/lib/ollama
