#!/usr/bin/sh

# Create docker group if it doesn't exist
getent group docker > /dev/null || groupadd -r docker

# Create docker service account if it doesn't exist
getent passwd docker > /dev/null || useradd -r -g docker -c "Docker Service Account" -d /var/lib/docker -s /usr/sbin/nologin docker

# Get current user and add to docker group
#current_user=$(who | awk '{print $1}' | sort -u | head -n1)
#if [ -n "$current_user" ] && [ "$current_user" != "root" ]; then
#    usermod -aG docker "$current_user"
#fi
